# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.6"
  - "3.5"

env:
  - DJANGO=1.11
  - DJANGO=2.0

matrix:
  fast_finish: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U setuptools tox-travis

# command to run tests using coverage, e.g. python setup.py test
script: tox

after_success:
  - codecov
